// Generated by AI

void TrieInsert(TrieNode trie, string word)
{
    var node = trie;
    foreach (var ch in word)
    {
        if (!node.Children.TryGetValue(ch, out var next))
        {
            next = new TrieNode();
            node.Children[ch] = next;
        }
        node = next;
    }
    node.IsEnd = true;
}

TrieNode BuildTrie(IEnumerable<string> patterns)
{
    var trie = new TrieNode();
    foreach (var p in patterns) TrieInsert(trie, p);
    return trie;
}

List<int> TrieMatches(TrieNode trie, string s, int start)
{
    var matches = new List<int>();
    var node = trie;
    for (int i = start; i < s.Length; i++)
    {
        if (!node.Children.TryGetValue(s[i], out var next)) break;
        node = next;
        if (node.IsEnd) matches.Add(i + 1);
    }
    return matches;
}

var lines = File.ReadAllLines("data.txt")
                 .Where(l => l.Length > 0)
                 .ToList();

var patterns = lines[0].Split(',').Select(p => p.Trim()).ToList();
var trie = BuildTrie(patterns);
var designs = lines.Skip(1).ToList();

var ways = new List<long>();

foreach (var design in designs)
{
    var totals = new long[design.Length + 1];
    totals[0] = 1;

    for (int newPos = 0; newPos < design.Length; newPos++)
    {
        long val = totals[newPos];
        if (val > 0)
        {
            foreach (var matchIndex in TrieMatches(trie, design, newPos))
            {
                totals[matchIndex] += val;
            }
        }
    }

    ways.Add(totals[design.Length]);
}

// Part 1
Console.WriteLine($"Ways: {ways.Count(x => x != 0)}");
// Part 2
Console.WriteLine($"Ways: {ways.Sum()}");

class TrieNode
{
    public Dictionary<char, TrieNode> Children = new();
    public bool IsEnd = false;
}